include:
    - compose-database.yaml

services:

    backend:
        container_name: spring
        ports:
            - '${SERVER_PORT:-8080}:8080'
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: private
            DB_USER: postgres
            DB_PASS: secret
        build:
            context: ./ # Use root context so Dockerfile can copy /src folder and /pom.xml file
            dockerfile: ./infra/spring/Dockerfile
        depends_on:
            postgresql: # Service declared on compose-database.yaml file
                condition: service_healthy

    redis:
        container_name: redis:7.4.1
        ports:
            - '6379:6379'
        image: redis
        environment:
            ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - ./infra/redis/redis_data:/data
